In [1]:
import numpy as np

In [2]:
dt = np.dtype([('Name', 'S10'), ('Age', 'i4'), ('Height', 'f'), ('Children/Pets', 'i4', 2)])

In [3]:
dt

dtype([('Name', 'S10'), ('Age', '<i4'), ('Height', '<f4'), ('Children/Pets', '<i4', (2,))])

In [4]:
s = np.array([('Smith', 45, 1.84, (0, 1)), ('Jones', 30, 1.73, (1, 2))], dtype=dt)

In [5]:
s

array([(b'Smith', 45, 1.84, [0, 1]), (b'Jones', 30, 1.73, [1, 2])],
      dtype=[('Name', 'S10'), ('Age', '<i4'), ('Height', '<f4'), ('Children/Pets', '<i4', (2,))])

In [6]:
type(s)

numpy.ndarray

In [7]:
s['Name']

array([b'Smith', b'Jones'], dtype='|S10')

In [8]:
s['Height'].mean()

1.7850001

In [9]:
s[0]

(b'Smith', 45, 1.84, [0, 1])

In [10]:
s[1]['Age']

30

In [11]:
np.random.seed(100)
r = np.arange(12).reshape((4,3))
s = np.arange(12).reshape((4,3))*0.5

In [12]:
r

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [13]:
s

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ],
       [4.5, 5. , 5.5]])

In [16]:
x = np.random.standard_normal((1000000, 5))
y = 2*x + 3
C = np.array((x, y), order='C')  #order by row
F = np.array((x, y), order='F')  #order by column
x = 0.0; y = 0.0
C[:2].round(2)

array([[[ 0.89,  0.51,  0.92,  0.79, -1.53],
        [ 0.85,  0.7 , -0.54,  0.06, -0.88],
        [ 1.23, -0.  ,  0.52,  0.28,  0.19],
        ...,
        [-0.31, -0.9 , -0.78,  1.3 , -0.36],
        [ 0.15, -0.69, -1.73,  1.47,  1.39],
        [ 0.86,  1.13, -0.91, -1.6 , -0.62]],

       [[ 4.78,  4.03,  4.84,  4.58, -0.07],
        [ 4.7 ,  4.4 ,  1.93,  3.12,  1.25],
        [ 5.45,  2.99,  4.04,  3.56,  3.38],
        ...,
        [ 2.38,  1.21,  1.43,  5.61,  2.28],
        [ 3.29,  1.62, -0.45,  5.94,  5.79],
        [ 4.72,  5.25,  1.18, -0.2 ,  1.77]]])

In [18]:
%timeit C.sum()

7.53 ms ± 468 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [19]:
timeit F.sum()

7.51 ms ± 419 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [20]:
C.shape

(2, 1000000, 5)